import { Clock, Zap, Crown, Diamond } from "lucide-react";

export const PLANS = [
  {
    id: 'trial',
    name: 'Trial',
    slug: 'trial',
    price: 0,
    period: '3 meses grátis',
    description: 'Comece sua jornada na plataforma',
    icon: Clock,
    color: 'slate', // Neutro - estabilidade
    gradient: 'from-slate-500 to-slate-600',
    iconBg: 'bg-slate-500/20',
    iconColor: 'text-slate-400',
    borderColor: 'border-slate-700',
    features: [
      'Perfil básico na plataforma',
      'Chat com alunos',
      'Limite de 10 aulas/mês',
      'Suporte por email',
    ],
    highlight: false,
    cta: 'Seu plano atual',
    disabled: true,
  },
  {
    id: 'essencial',
    name: 'Essencial',
    slug: 'essencial',
    price: 79.90,
    period: '/mês',
    description: 'Para instrutores comprometidos',
    icon: Zap,
    color: 'blue', // Azul - confiança, profissionalismo
    gradient: 'from-blue-500 to-blue-600',
    iconBg: 'bg-blue-500/20',
    iconColor: 'text-blue-400',
    borderColor: 'border-blue-500/50',
    checkColor: 'text-blue-400',
    features: [
      'Perfil completo na plataforma',
      'Aulas ilimitadas',
      'Selo "Ativo" no perfil',
      'Chat prioritário com alunos',
      'Suporte por email e chat',
    ],
    highlight: false,
    cta: 'Assinar Essencial',
  },
  {
    id: 'destaque',
    name: 'Destaque',
    slug: 'destaque',
    price: 149.90,
    period: '/mês',
    description: 'Apareça para mais alunos',
    icon: Crown,
    color: 'emerald', // Verde - crescimento, sucesso
    gradient: 'from-emerald-500 to-teal-500',
    iconBg: 'bg-emerald-500/20',
    iconColor: 'text-emerald-400',
    borderColor: 'border-emerald-500/50',
    checkColor: 'text-emerald-400',
    features: [
      'Tudo do Essencial',
      'Top 10 nas buscas da sua região',
      'Analytics de visualizações',
      'Badge "Destaque" no perfil',
      'Suporte prioritário',
    ],
    highlight: true,
    cta: 'Assinar Destaque',
  },
  {
    id: 'elite',
    name: 'Elite',
    slug: 'elite',
    price: 249.90,
    period: '/mês',
    description: 'Máxima visibilidade',
    icon: Diamond,
    color: 'amber', // Dourado - premium, exclusividade
    gradient: 'from-amber-400 via-yellow-500 to-orange-500',
    iconBg: 'bg-gradient-to-br from-amber-400/30 to-orange-500/30',
    iconColor: 'text-amber-400',
    borderColor: 'border-amber-500/50',
    checkColor: 'text-amber-400',
    features: [
      'Tudo do Destaque',
      'Top 5 nas buscas da sua região',
      'Selo "Verificado" dourado',
      'Perfil com destaque visual',
      'Suporte VIP 24h',
      'Consultoria de perfil mensal',
    ],
    highlight: false,
    cta: 'Assinar Elite',
  },
];
